### ISSUE TITLE
Distinguish between "good" and "bad" errors for invalid test cases

### ISSUE THREAD

**Issue by johnvtan** [nlsandler/writing-a-c-compiler-tests#26]
It seems like `test_compiler` will accept any non-zero error code for invalid test cases. It would be nice if it could distinguish between a "good" or expected error in the compiler, and a "bad"/unexpected error (e.g., a segfault). `test_compiler` could accept a new argument that lets the user specify the expected error code for invalid test cases.

**Comment by nlsandler** [comment]
Added an `--expected-error-codes` option to do this - @johnvtan, give it a try and let me know how it goes!

**Comment by johnvtan** [comment]
Thanks! I often return -1 in the case of an error, but when I pass -1 to `--expected-error-codes`, it fails because bash converts negative return values into 8 bit unsigned integers. Could the script also convert the error code into an 8 bit unsigned integer, or otherwise throw an error if value for `--expected-error-codes` is outside [0, 255]?

**Comment by nlsandler** [comment]
Ah, good point! Requiring error codes to be in range [0, 255] (or I guess [1, 255]) seems like the most straightforward way to handle this - I'll make that update.
