### ISSUE TITLE
Preserve generated assembly file on test errors

### ISSUE THREAD

**Issue by johnvtan** [nlsandler/writing-a-c-compiler-tests#27]
If a test case fails, I pretty much always end up re-running my compiler driver script to generate the assembly file. It would be helpful if `test_compiler` automatically stored the generated assembly file somewhere for the user to look at and debug after failed test cases.

I don't think having an option to generate the assembly file is part of the specification for the compiler driver in the book though. Maybe `test_compiler` needs a new argument to tell it what argument the compiler driver script uses to generate assembly?

**Comment by nlsandler** [comment]
The specification for the compiler driver suggests using `-S` to generate assembly but not assemble/link it. (This is a suggestion in Part I and a requirement in Part III.) I think it would be straightforward to add an option to `test_compiler` to have it just invoke the compiler again on any failed tests, this time with the `-S` option to preserve their assembly.

**Comment by nlsandler** [comment]
Added a `--keep-asm-on-failure` option that does this; let me know if you run into any issues with it!

**Comment by johnvtan** [comment]
This is great, thanks!
