### ISSUE TITLE
Shift operators require typed registers

### ISSUE THREAD

**Issue by tyehle** [nlsandler/writing-a-c-compiler-tests#28]
Implementing the `>>` and `<<` at the end of chapter 3 requires use of a single byte register. I skipped ahead to see how register types would fit into the data model so I didn't have to refactor all that when I got there and ended up with this temporary hack:
```racket
  (define operand->string
    (match-lambda
      ; typed register. There is only one for now so we can support shifts
      [`(reg CX 1 ,_) "%cl"]
      ; untyped registers
      [`(reg AX ,_) "%eax"]
      [`(reg CX ,_) "%ecx"]
      ...
```

A pointer about how typed registers will be handled would be helpful at the end of chapter 3.

**Comment by nlsandler** [comment]
This is a good point. I think there may be one or two other extra credit features that would benefit from hints about how thing are handled later. (The other case I'm thinking of is that in compound assignment operators like `a += b`, `a` must only be evaluated once - which means ways of rewriting the AST that seem workable become a problem once you implement more complex lvalues like `a[i]` or `a.member` in Part II.)

It's too late to update the chapters, but maybe the web page should include an "Extra Credit Hints" section.

**Comment by nlsandler** [comment]
Added to the webpage: https://norasandler.com/book/#tips-on-extra-credit-features. Does that cover it?
(It's possible that I'd be able to add this to the book itself in the next reprint)

**Comment by tyehle** [comment]
That looks great!
