### ISSUE TITLE
Missing test: function called with too few arguments

### ISSUE THREAD

**Issue by meithecatte** [nlsandler/writing-a-c-compiler-tests#29]
There's currently `tests/chapter_9/invalid_types/too_many_args.c`, which makes sure that the compiler correctly detects the case where too many arguments are passed to a function. I couldn't find any testcase that tests for the opposite situation: not enough arguments.

I'd argue that there's value in having a separate test for this – it's easy to imagine an asymmetric implementation where one of the cases would be detected, but the other wouldn't.

**Comment by nlsandler** [comment]
Yup, I think it's worth having a test case for this. Thanks for reporting it!
