### ISSUE TITLE
chapter_9/invalid_parse/fun_decl_for_loop.c seems to be marked as invalid without reason

### ISSUE THREAD

**Issue by meithecatte** [nlsandler/writing-a-c-compiler-tests#32]
The test claims that

> Function declarations aren't permitted in for loop headers.

However, I can't find anything in the standard about this. Indeed, GCC accepts the code, only emitting a warning if enabled with `-pedantic`.

**Comment by nlsandler** [comment]
The relevant part of the standard is 6.8.5, paragraph 3:

> The declaration part of a `for` statement shall only declare identifiers for objects having storage class
`auto` or `register`.

Clang also treats this as an error: https://godbolt.org/z/c8dMa4rM5

FWIW, this test suite covers quite a few constraint violations that GCC warns on only with `-pedantic`.

**Comment by meithecatte** [comment]
Ah, you're right. The key is to notice that "object" is a technical term:

> 6.2.5p1 Types are partitioned into object types and function types.
