### ISSUE TITLE
Spaces in file path cause Python Exception

### ISSUE THREAD

**Issue by picworker** [nlsandler/writing-a-c-compiler-tests#44]
OS Paths should be enclosed in quotes to prevent the path breaking at spaces.
The test crashed repeatedly with messages like this:

```
$ ../../writing-a-c-compiler-tests/test_compiler --chapter 1 compiler_driver.py
======================================================================
FAIL: test_valid/multi_digit (test_framework.basic.TestChapter1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/Users/id1234/OneDrive - My Company Inc/apps/books/WritingACCompiler/writing-a-c-compiler-tests/test_framework/basic.py", line 563, in test_run
    self.compile_and_run(program)
  File "/mnt/c/Users/id1234/OneDrive - My Company Inc/apps/books/WritingACCompiler/writing-a-c-compiler-tests/test_framework/basic.py", line 345, in compile_and_run
    self.assertEqual(
AssertionError: compilation of /mnt/c/Users/id1234/OneDrive - My Company Inc/apps/books/WritingACCompiler/writing-a-c-compiler-tests/tests/chapter_1/valid/multi_digit.c failed with error:
gcc: fatal error: input file ‘/mnt/c/Users/id1234/OneDrive’ is the same as output file
compilation terminated.


======================================================================
FAIL: test_valid/newlines (test_framework.basic.TestChapter1)
----------------------------------------------------------------------
```

**Comment by nlsandler** [comment]
This may be a bug in your compiler driver, rather than the test script. What happens when you use `driver.py` to compile one of the test programs directly, without using the test script?

**Comment by picworker** [comment]
Hello and thanks for the quick reply.

My 1st pass of `compiler_driver.py` is quite crude and only works in the current directory.  So it is unlikely to trip up on a distance path parent having spaces.

Running from the executable directory.  The error is due to my lazy parsing of the input file name split("."):
```
$ ./compiler_driver.py ../../writing-a-c-compiler-tests/tests/chapter_1/valid/return_2.c
gcc: fatal error: output filename may not be empty
```
Running from the test file directory (the error is due to the compiler not existing yet):
```
$ ../../../../work/chap_01/compiler_driver.py return_2.c
Assembler messages:
Error: can't open return_2.s for reading: No such file or directory
```

Enjoying the book.  The hardcopy version arrives on Monday.

**Comment by nlsandler** [comment]
Thanks for replying, and glad to hear you're enjoying the book!

What happens when you pass it an absolute path? Like:

```
$ ./compiler_driver.py "/mnt/c/Users/id1234/OneDrive - My Company Inc/apps/books/WritingACCompiler/writing-a-c-compiler-tests/tests/chapter_1/valid/return_2.c"
```

**Comment by picworker** [comment]
Yes you are correct, the reported issue is in my `compiler_driver.py` code.  I suggested a fix to your code, that I had not implemented in my own code.  Even as we discussed it, it took me a while to see it.

Please close this issue as user error.  Thank you for your time.

**Comment by nlsandler** [comment]
Gotcha, thanks for confirming!
