### ISSUE TITLE
`--chapter 1 --stage lex` runs invalid_parse

### ISSUE THREAD

**Issue by xqb64** [nlsandler/writing-a-c-compiler-tests#70]
Is it expected behavior that running the test suite with `--chapter 1 --stage lex` runs examples within the invalid_parse directory?  I've only written a tokenizer, and am trying to test it, but my tests are failing for something that should be solved at a parser level.

**Comment by mattdaw** [comment]
I ran into this as well.

**Comment by nlsandler** [comment]
Ah, it sounds like your compiler might not be preprocessing the file before lexing it. There's more info about how to do that on p.7 in the "Compiler Driver" section, but let me know if that doesn't resolve your issue.

**Comment by xqb64** [comment]
Unfortunately, the lexing crate I'm using (logos) does not currently support lookaround assertions.  I'll need to whip up my own tokenizer.  Thanks for the response, @nlsandler.  Love the book.  This issue can be closed as far as I'm concerned.

**Comment by mattdaw** [comment]
I've identified the problem in how I was calling the preprocessor, all good now. Thanks @nlsandler! Good to close for me now too.

**Comment by nlsandler** [comment]
Great, thank you both!
