### ISSUE TITLE
Compiler "failing" even though it is returning 0 for the case

### ISSUE THREAD

**Issue by SunilPaul174** [nlsandler/writing-a-c-compiler-tests#81]
I'm not sure if i have structured my driver wrong or something, but the program is failing tests even though when run individually, it is returning 0.
![Screenshot_20240923_091404](https://github.com/user-attachments/assets/521dc3a3-f2bc-4271-8ae4-514fc57a551e)
The tests failed are:
```
test_framework.basic.TestChapter1.test_valid/multi_digit
test_framework.basic.TestChapter1.test_valid/newlines
test_framework.basic.TestChapter1.test_valid/no_newlines
test_framework.basic.TestChapter1.test_valid/return_0
test_framework.basic.TestChapter1.test_valid/return_2
test_framework.basic.TestChapter1.test_valid/spaces
test_framework.basic.TestChapter1.test_valid/tabs
```

**Comment by SunilPaul174** [comment]
```./test_compiler ./compiler --chapter 1 --stage parse```
Where compiler is the rust binary i have copied `target/release/<cratename>` into the repository directory of these tests

**Comment by SunilPaul174** [comment]
![image](https://github.com/user-attachments/assets/298730f1-a302-4251-86d3-40da0a628f4d)
information about the machine, if it's necessary

**Comment by nlsandler** [comment]
Thanks!

The test script invokes your compiler with the `--codegen` option first, before the source file name. Does your compiler driver expect `--codegen` to come last? That could  the issue you're seeing.

**Comment by SunilPaul174** [comment]
It does, i'll try restructuring it.

**Comment by SunilPaul174** [comment]
Thank you! After some unrelated bug fixes to the compiler, putting the option for the compiler before the file works!
![image](https://github.com/user-attachments/assets/95b86694-555a-4195-8c1c-daa4eeb0e751)
I'll be closing this issue now.

**Comment by nlsandler** [comment]
I'm glad you got this working! And thanks again for filing it - it pointed out a usability issue with the test script.

**Comment by SunilPaul174** [comment]
No problem! Thank you for your hard work.
