### ISSUE TITLE
Tests in chapter 4 contain not introduced tokens

### ISSUE THREAD

**Issue by Leinnan** [nlsandler/writing-a-c-compiler-tests#84]
Starting from Chapter 4 some of the files does have this code:
```c
#ifdef SUPPRESS_WARNINGS
#ifndef __clang__
#pragma GCC diagnostic ignored "-Wparentheses"
#endif
#endif
```
For me, calling `../writing-a-c-compiler-tests/test_compiler ./target/debug/ulang_driver --chapter 4 --stage lex` results in failure due to that code. I guess for now I can ignore any line starting with `#` like I do for lines with `//` but should I? Maybe I skipped/forgot some instruction from previous chapter, but it is hard to tell. 

It would be useful to know how to handle that code at this moment in the book.

**Comment by nlsandler** [comment]
I'm closing this issue, but feel free to re-open if you're still having issues with the preprocessor!
