### ISSUE TITLE
Missing test case: duplicate label definition

### ISSUE THREAD

**Issue by meithecatte** [nlsandler/writing-a-c-compiler-tests#9]
Hello! I'm following along with the test-suite, but not the book – I feel like this might be a useful disclaimer.

I believe there's a test missing in `chapter_6/invalid_semantics/extra_credit` testing for the case when a label has multiple definitions – c.f. N1570 6.8.1.3:

> Label names shall be unique within a function.

**Comment by nlsandler** [comment]
You're correct, there should be a test case for this. (The extra-credit tests aren't finished yet, so there are currently a lot of missing test cases for these features.)

**Comment by nlsandler** [comment]
I've pushed a couple of test cases for this to `complete-test-suite`; let me know if you run into issues with any of them! (I'll leave this issue open until they're merged into main)
